# Generated by Django 5.0.8 on 2024-12-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=100)),
                ("fact", models.TextField()),
                ("image_url", models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FunFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fact", models.TextField()),
                ("category", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Joke",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setup", models.TextField()),
                ("punchline", models.TextField()),
                ("category", models.CharField(default="general", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image_url", models.URLField()),
                ("abilities", models.JSONField()),
                ("types", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("ingredients", models.JSONField()),
                ("instructions", models.TextField()),
                ("cooking_time", models.CharField(max_length=50)),
                ("difficulty", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ScienceExperiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("materials", models.JSONField()),
                ("steps", models.TextField()),
                ("safety_notes", models.TextField()),
                ("age_group", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SpaceInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("type", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("moral", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TriviaQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("correct_answer", models.CharField(max_length=255)),
                ("incorrect_answers", models.JSONField()),
                ("category", models.CharField(max_length=100)),
                ("difficulty", models.CharField(max_length=50)),
            ],
        ),
    ]
