# Generated by Django 5.0.8 on 2024-12-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Çocuk", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aktivite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("aciklama", models.TextField()),
                ("kategori", models.CharField(max_length=100)),
                ("resim_url", models.URLField(blank=True)),
                ("yas_grubu", models.CharField(max_length=50)),
                ("olusturulma_tarihi", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BilmeceBulmaca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tur", models.CharField(max_length=100)),
                ("soru", models.TextField()),
                ("cevap", models.CharField(max_length=500)),
                ("zorluk", models.CharField(max_length=50)),
                ("ipucu", models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="DenemeyeGeldi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("malzemeler", models.TextField()),
                ("adimlar", models.TextField()),
                ("sure", models.CharField(max_length=50)),
                ("zorluk", models.CharField(max_length=50)),
                ("guvenlik_notu", models.TextField()),
                ("video_url", models.URLField(blank=True)),
                ("sonuc_aciklamasi", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DogaBilgisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("kategori", models.CharField(max_length=100)),
                ("icerik", models.TextField()),
                ("ilginc_bilgi", models.TextField()),
                ("resim_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("kaynak", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="EgitimIcerigi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("konu", models.CharField(max_length=100)),
                ("sinif_duzeyi", models.CharField(max_length=50)),
                ("icerik", models.TextField()),
                ("video_url", models.URLField(blank=True)),
                ("dosya_url", models.URLField(blank=True)),
                ("sure", models.CharField(max_length=50)),
                ("ogrenim_hedefleri", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ElSanatlari",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proje_adi", models.CharField(max_length=200)),
                ("zorluk", models.CharField(max_length=50)),
                ("sure", models.CharField(max_length=50)),
                ("malzemeler", models.TextField()),
                ("yapilis_adimlari", models.TextField()),
                ("yas_grubu", models.CharField(max_length=50)),
                ("resim_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="HikayeMasallar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("baslik", models.CharField(max_length=200)),
                ("tur", models.CharField(max_length=100)),
                ("icerik", models.TextField()),
                ("yazar", models.CharField(max_length=200)),
                ("okuma_suresi", models.CharField(max_length=50)),
                ("yas_grubu", models.CharField(max_length=50)),
                ("sesli_hikaye_url", models.URLField(blank=True)),
                ("anahtar_kelimeler", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="YemekTarifi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=200)),
                ("zorluk", models.CharField(max_length=50)),
                ("hazirlama_suresi", models.CharField(max_length=50)),
                ("pisirme_suresi", models.CharField(max_length=50)),
                ("malzemeler", models.TextField()),
                ("yapilis", models.TextField()),
                ("besin_degeri", models.TextField()),
                ("resim_url", models.URLField(blank=True)),
                ("video_url", models.URLField(blank=True)),
                ("cocuk_dostu", models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Animal",
        ),
        migrations.DeleteModel(
            name="FunFact",
        ),
        migrations.DeleteModel(
            name="Joke",
        ),
        migrations.DeleteModel(
            name="Pokemon",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.DeleteModel(
            name="ScienceExperiment",
        ),
        migrations.DeleteModel(
            name="SpaceInfo",
        ),
        migrations.DeleteModel(
            name="Story",
        ),
        migrations.DeleteModel(
            name="TriviaQuestion",
        ),
    ]
