# Generated by Django 5.0.8 on 2024-12-27 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Çocuk", "0002_aktivite_bilmecebulmaca_denemeyegeldi_dogabilgisi_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EgitimIcerigi",
        ),
    ]
